
    // This file is auto-generated by the readImages.js script.
    export const imageFileNames = ["../../../assets/banner/banner 1.jpeg", "../../../assets/banner/image1fan.png", "../../../assets/banner/image2fan.jpg"];
    