name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm cache clean --force && npm install --ci

      - name: Build project
        run: npm run build-dev

      - name: FTP Deploy
        run: |
          echo "Uploading files to cPanel..."
          lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R ./dist/ /"
